---
mysql:
  config:
    user: mysql
    port: 3306
    datadir: /var/lib/mysql
    bind: 0.0.0.0
    pid: /var/run/mysqld/mysqld.pid
    socket: /var/run/mysqld/mysql.sock
    cnfpath: /etc/my.cnf
  service: mysqld
  pkg: 
    server: mysql-server
    client: mysql-client
    python: python-mysqldb
  server: true
